name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install sfdx-cli
      - name: Authenticate devhub
        run: |
          echo "${{ secrets.SALESFORCE_JWT_SECRET_KEY }}" > server.key
          node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.SALESFORCE_DEVHUB_USERNAME}} --setdefaultdevhubusername --setalias devhub
      - name: Deploy source
        run: node_modules/sfdx-cli/bin/run force:source:push
      - name: Run Apex test
        run: node_modules/sfdx-cli/bin/run force:apex:test:run --codecoverage --resultformat human
