name: CI

on:
  push:
    paths-ignore:
      - README.md
      - "**/README.md"

env:
  PACKAGENAME: packaging-ci-demo-ns

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install sfdx-cli@7.45
      - name: Authenticate devhub
        run: |
          echo "${{ secrets.SALESFORCE_JWT_SECRET_KEY }}" > server.key
          node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.SALESFORCE_DEVHUB_USERNAME}} --setdefaultdevhubusername --setalias devhub
      - name: Create scratch org
        run: node_modules/sfdx-cli/bin/run force:org:create --targetdevhubusername devhub --setdefaultusername --definitionfile config/project-scratch-def.json --setalias ciorg --durationdays 1
      - name: Deploy source
        run: node_modules/sfdx-cli/bin/run force:source:push
      - name: Run Apex tests
        run: node_modules/sfdx-cli/bin/run force:apex:test:run --codecoverage --resultformat human
      - name: Run frontend tests
        run: |
          npm install @salesforce/sfdx-lwc-jest
          npm run test:unit
      - name: Delete scratch org
        run: node_modules/sfdx-cli/bin/run force:org:delete --noprompt
      - name: Create new package version and release
        id: create_package
        if: github.ref == 'refs/heads/master'
        run: |
          NEXTVERSION="$(python ci/get-next-version.py "$(sfdx force:package:version:list -p packaging-ci-demo-ns -r -o CreatedDate | tail -1 | awk '{print $4}')")"
          PACKAGEVERSIONID="$(node_modules/sfdx-cli/bin/run force:package:version:create --package $PACKAGENAME -a $NEXTVERSION -n $NEXTVERSION -x --json --targetdevhubusername devhub --wait 10  | jq -r '.result.SubscriberPackageVersionId')"
          echo ${PACKAGEVERSIONID}
          node_modules/sfdx-cli/bin/run force:package:version:promote -p ${PACKAGEVERSIONID} -n
          PACKAGEVERSION="$(node_modules/sfdx-cli/bin/run force:package:version:report -p $PACKAGEVERSIONID --json | jq -r '.result.Version')"
          echo "::set-output name=package_version::${PACKAGEVERSION}"
      - name: Create release
        uses: actions/create-release@v1
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_package.outputs.package_version }}
          release_name: Release ${{ steps.create_package.outputs.package_version }}
          draft: false
          prerelease: false
